spring:
  application:
    name: medical-doc-agent-workflow
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8
  datasource:
    url: jdbc:mysql://localhost:3309/course_ehealth?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: Zxy@5628610
    driver-class-name: com.mysql.cj.jdbc.Driver

google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    com.example.service.WorkflowService: DEBUG
    root: INFO

mybatis:
  configuration:
    map-underscore-to-camel-case: true
