@clientId = 1

### 查询所有客户
GET http://localhost:8080/api/clients
Accept: application/json

###

### ⭐ 根据ID查询客户
GET http://localhost:8080/api/clients/{{clientId}}
Accept: application/json

###

### ⭐ 根据ID查询客户所有的的Prescriptions
GET http://localhost:8080/api/prescriptions/client/{{clientId}}
Accept: application/json

### ⭐ 根据ID查询客户所有的的Requisitions
GET http://localhost:8080/api/requisitions/client/{{clientId}}
Accept: application/json

###

### ⭐ 删除该客户的所有Prescriptions
DELETE http://localhost:8080/api/prescriptions/client/{{clientId}}
Accept: application/json

### ⭐ 删除该客户的所有Requisitions
DELETE http://localhost:8080/api/requisitions/client/{{clientId}}
Accept: application/json

###

### 新增客户
POST http://localhost:8080/api/clients
Content-Type: application/json

{
  "firstName": "测试客户",
  "email": "test@example.com"
}

###

### 更新客户
PUT http://localhost:8080/api/clients
Content-Type: application/json

{
  "id": 1,
  "name": "client1-updated",
  "email": "updated@example.com"
}

###

### 删除客户
DELETE http://localhost:8080/api/clients/{{clientId}}
Accept: application/json
